packages:
- ./

# Docker image 0.1.1 brings it up to 8.2 instead of 8.1:
resolver: ghc-8.2
compiler: ghc-8.2
system-ghc: true

# # Trying intero-0.1.20, no luck yet.
# skip-ghc-check: true
# allow-newer: true
# extra-deps:
# - ghc-paths-0.1.0.9
# - syb-0.7
#    # /tmp/stack1/intero-0.1.20/src/GhciMonad.hs:302:52: error:
#    #      Not in scope: type constructor or class ‘GHC.RunResult’
#    #      A data constructor of that name is in scope; did you mean DataKinds?
#    #      Module ‘GHC’ does not export ‘RunResult’.
#    #      |
#    #  302 | runStmt :: String -> GHC.SingleStep -> GHCi (Maybe GHC.RunResult)
#    #      |                                                    ^^^^^^^^^^^^^


docker:
  enable: true
  # GHC 8.1 
#  image: parfunc/linear-types:0.0.2
  # GHC 8.2.X rebase
  image: tweag/linear-types:0.1.2
